// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockMap: typeof import('./components/block-map.vue')['default']
    CropGrowth: typeof import('./components/crop-growth.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GrainStorage: typeof import('./components/grain-storage.vue')['default']
    HomeHeader: typeof import('./components/home-header.vue')['default']
    LineView: typeof import('./components/line-view.vue')['default']
    MachineInfo: typeof import('./components/machine-info.vue')['default']
    MainMap: typeof import('./components/main-map.vue')['default']
    OperationProgress: typeof import('./components/operation-progress.vue')['default']
    OutputStatistics: typeof import('./components/output-statistics.vue')['default']
    OverView: typeof import('./components/over-view.vue')['default']
    ProjectMap: typeof import('./components/project-map.vue')['default']
    ProjectMapView: typeof import('./components/project-map-view.vue')['default']
    ProportionCrops: typeof import('./components/proportion-crops.vue')['default']
    RevenueGrowth: typeof import('./components/revenue-growth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCustom: typeof import('./components/select-custom.vue')['default']
    ViewTitle: typeof import('./components/view-title.vue')['default']
    WorkBench: typeof import('./components/work-bench.vue')['default']
  }
}
